### ISSUE TITLE
Unit of Area in the dataset

### ISSUE THREAD

**Issue by Shruthi-Patil** [Lkruitwagen/solar-pv-global-inventory#11]
Hi, 
I'm looking at `predicted_set.geojson` on [zenodo](https://zenodo.org/record/5005868#.Ys6tA3ZBzUQ). The capacity is mentioned to be in MW. However, the unit of area is not mentioned. Could you please clarify if this is in square kilometers?

Thanks

**Comment by Lkruitwagen** [comment]
Hi Shruthi - thanks for your question. I believe the area unit is square meters, calculated using the [pypi area package](https://pypi.org/project/area/)

**Comment by Shruthi-Patil** [comment]
Thanks for the clarification!
